### ISSUE TITLE
Doesn't compile with GHC 9.10

### ISSUE THREAD

**Issue by spacekitteh** [tek/incipit-core#4]
```
[14 of 15] Compiling Incipit.TypeError ( lib/Incipit/TypeError.hs, dist/build/Incipit/TypeError.o, dist/build/Incipit/TypeError.dyn_o )
lib/Incipit/TypeError.hs:32:15: error: [GHC-91028]
    • Expected kind ‘forall k. k’,
        but ‘TypeError ('Text "undefined")’ has kind ‘b0’
      Cannot instantiate unification variable ‘b0’
      with a kind involving polytypes: forall k. k
    • In the type ‘TypeError ('Text "undefined")’
      In the type family declaration for ‘Undefined’
   |
32 |   Undefined = TypeError ('Text "undefined")
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
